const images_folder = process.env.REACT_APP_environment === "development" ? process.env.REACT_APP_host_url + "/assets" : process.env.REACT_APP_host_url_live + "/assets"
const api_url = process.env.REACT_APP_environment === "development" ? process.env.REACT_APP_api_url : process.env.REACT_APP_api_url_live

const reproductive_constants = [
    {
        title:"Support Adolescent Sexual Reproductive Health Project in Mombasa and Kilifi (TIKO Platform)",
        wall:images_folder + "/projects/reproductive1.jpg",
        wall2:images_folder + "/projects/reproductive1.jpg",
        body:`
                The project is supporting adolescent girls to access Sexual and Reproductive Health Services in Mombasa and Kilifi Counties.
                CWID partnership with Triggerise is to achieve;
                ~Recruit Mobilisers to generate demand for contraception and HIV testing among young adolescent
                ~ Girls aged 15-19 to take up contraception or HIV testing and refer adolescent for such services among approved service providers.
                ~ Train Mobiliser using standard guidelines, tools, IEC materials and other collateral to be provided by triggerise.
                ~Supervise mobilizers recruited to ensure that they comply with the standard code of conduct.
                ~ Undertake actions to engage communities in the localities in which they operate so that they are aware of the project including its goals and are support of its aim;
                ~ Ensure that there is minimum number of trained mobilizers focused on supporting the project.
                ~ undertake actions that safeguards and protects girls that take up contraception and HIV testing services through the project.
                ~ utilize insights generated by triggerise through its technology platform on the performance of their mobilizers to strengthen the quality of supervision and support they provide.
                <h2>Achievements</h2>

                Triggerise platform has achieved so far to reach 4 wards within Mombasa County that is; Magogoni, Junda, ziwa la ngombe and Mtopanga ward. The project that support adolescents Sexual reproductive health has also achieved to reach 86 young girls who are currently taking service within the 4 wards reached in Mombasa County.  This performance is specific result achieved by CWID organization through the continuous partnership with Triggerise organization.
        `
    }
]

            export const select_reproductive = async() => {
                try{
                    const res = await fetch(api_url + "/wireframe",
                        {
                            method:"POST",
                            headers : {'Content-type': 'application/json; charset=UTF-8'},
                            body:JSON.stringify({component:"projects",list:reproductive_constants,count:10})
                        }
                    )
                
                    const {status, data} = await res.json()
                
                    if(status)
                        return data[0]
                    else
                        return reproductive_constants[0]
                }catch(error){
                    console.log(error)
                    return reproductive_constants[0]
                }
        
            }

export default reproductive_constants